// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod pkg {
        pub mod component {
            #[allow(dead_code, clippy::all)]
            pub mod component_tcp {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct ComponentIpSocketAddress {
                    handle: _rt::Resource<ComponentIpSocketAddress>,
                }
                type _ComponentIpSocketAddressRep<T> = Option<T>;
                impl ComponentIpSocketAddress {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `ComponentIpSocketAddress`.
                    pub fn new<T: GuestComponentIpSocketAddress>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _ComponentIpSocketAddressRep<T> = Some(val);
                        let ptr: *mut _ComponentIpSocketAddressRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestComponentIpSocketAddress>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestComponentIpSocketAddress>(
                        &mut self,
                    ) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestComponentIpSocketAddress>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: u32) -> Self {
                        Self {
                            handle: _rt::Resource::from_handle(handle),
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> u32 {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> u32 {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = _rt::Box::from_raw(
                            handle as *mut _ComponentIpSocketAddressRep<T>,
                        );
                    }
                    fn as_ptr<T: GuestComponentIpSocketAddress>(
                        &self,
                    ) -> *mut _ComponentIpSocketAddressRep<T> {
                        ComponentIpSocketAddress::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`ComponentIpSocketAddress`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct ComponentIpSocketAddressBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a ComponentIpSocketAddress>,
                }
                impl<'a> ComponentIpSocketAddressBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestComponentIpSocketAddress>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(
                        &self,
                    ) -> *mut _ComponentIpSocketAddressRep<T> {
                        ComponentIpSocketAddress::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for ComponentIpSocketAddress {
                    #[inline]
                    unsafe fn drop(_handle: u32) {
                        #[cfg(not(target_arch = "wasm32"))]
                        unreachable!();
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]pkg:component/component-tcp"
                            )]
                            extern "C" {
                                #[link_name = "[resource-drop]component-ip-socket-address"]
                                fn drop(_: u32);
                            }
                            drop(_handle);
                        }
                    }
                }
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct ComponentPollable {
                    handle: _rt::Resource<ComponentPollable>,
                }
                type _ComponentPollableRep<T> = Option<T>;
                impl ComponentPollable {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `ComponentPollable`.
                    pub fn new<T: GuestComponentPollable>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _ComponentPollableRep<T> = Some(val);
                        let ptr: *mut _ComponentPollableRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestComponentPollable>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestComponentPollable>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestComponentPollable>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: u32) -> Self {
                        Self {
                            handle: _rt::Resource::from_handle(handle),
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> u32 {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> u32 {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = _rt::Box::from_raw(
                            handle as *mut _ComponentPollableRep<T>,
                        );
                    }
                    fn as_ptr<T: GuestComponentPollable>(
                        &self,
                    ) -> *mut _ComponentPollableRep<T> {
                        ComponentPollable::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`ComponentPollable`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct ComponentPollableBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a ComponentPollable>,
                }
                impl<'a> ComponentPollableBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestComponentPollable>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _ComponentPollableRep<T> {
                        ComponentPollable::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for ComponentPollable {
                    #[inline]
                    unsafe fn drop(_handle: u32) {
                        #[cfg(not(target_arch = "wasm32"))]
                        unreachable!();
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]pkg:component/component-tcp"
                            )]
                            extern "C" {
                                #[link_name = "[resource-drop]component-pollable"]
                                fn drop(_: u32);
                            }
                            drop(_handle);
                        }
                    }
                }
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct ComponentNetwork {
                    handle: _rt::Resource<ComponentNetwork>,
                }
                type _ComponentNetworkRep<T> = Option<T>;
                impl ComponentNetwork {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `ComponentNetwork`.
                    pub fn new<T: GuestComponentNetwork>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _ComponentNetworkRep<T> = Some(val);
                        let ptr: *mut _ComponentNetworkRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestComponentNetwork>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestComponentNetwork>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestComponentNetwork>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: u32) -> Self {
                        Self {
                            handle: _rt::Resource::from_handle(handle),
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> u32 {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> u32 {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = _rt::Box::from_raw(
                            handle as *mut _ComponentNetworkRep<T>,
                        );
                    }
                    fn as_ptr<T: GuestComponentNetwork>(
                        &self,
                    ) -> *mut _ComponentNetworkRep<T> {
                        ComponentNetwork::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`ComponentNetwork`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct ComponentNetworkBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a ComponentNetwork>,
                }
                impl<'a> ComponentNetworkBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestComponentNetwork>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _ComponentNetworkRep<T> {
                        ComponentNetwork::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for ComponentNetwork {
                    #[inline]
                    unsafe fn drop(_handle: u32) {
                        #[cfg(not(target_arch = "wasm32"))]
                        unreachable!();
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]pkg:component/component-tcp"
                            )]
                            extern "C" {
                                #[link_name = "[resource-drop]component-network"]
                                fn drop(_: u32);
                            }
                            drop(_handle);
                        }
                    }
                }
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct ComponentTcpSocket {
                    handle: _rt::Resource<ComponentTcpSocket>,
                }
                type _ComponentTcpSocketRep<T> = Option<T>;
                impl ComponentTcpSocket {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `ComponentTcpSocket`.
                    pub fn new<T: GuestComponentTcpSocket>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _ComponentTcpSocketRep<T> = Some(val);
                        let ptr: *mut _ComponentTcpSocketRep<T> = _rt::Box::into_raw(
                            _rt::Box::new(val),
                        );
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }
                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestComponentTcpSocket>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestComponentTcpSocket>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }
                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestComponentTcpSocket>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }
                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: u32) -> Self {
                        Self {
                            handle: _rt::Resource::from_handle(handle),
                        }
                    }
                    #[doc(hidden)]
                    pub fn take_handle(&self) -> u32 {
                        _rt::Resource::take_handle(&self.handle)
                    }
                    #[doc(hidden)]
                    pub fn handle(&self) -> u32 {
                        _rt::Resource::handle(&self.handle)
                    }
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(! cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => {
                                    assert!(
                                        ty == id, "cannot use two types with this resource type"
                                    )
                                }
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }
                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = _rt::Box::from_raw(
                            handle as *mut _ComponentTcpSocketRep<T>,
                        );
                    }
                    fn as_ptr<T: GuestComponentTcpSocket>(
                        &self,
                    ) -> *mut _ComponentTcpSocketRep<T> {
                        ComponentTcpSocket::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }
                /// A borrowed version of [`ComponentTcpSocket`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct ComponentTcpSocketBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a ComponentTcpSocket>,
                }
                impl<'a> ComponentTcpSocketBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }
                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestComponentTcpSocket>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }
                    fn as_ptr<T: 'static>(&self) -> *mut _ComponentTcpSocketRep<T> {
                        ComponentTcpSocket::type_guard::<T>();
                        self.rep.cast()
                    }
                }
                unsafe impl _rt::WasmResource for ComponentTcpSocket {
                    #[inline]
                    unsafe fn drop(_handle: u32) {
                        #[cfg(not(target_arch = "wasm32"))]
                        unreachable!();
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]pkg:component/component-tcp"
                            )]
                            extern "C" {
                                #[link_name = "[resource-drop]component-tcp-socket"]
                                fn drop(_: u32);
                            }
                            drop(_handle);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_constructor_component_ip_socket_address_cabi<
                    T: GuestComponentIpSocketAddress,
                >(arg0: i32, arg1: i32, arg2: i32, arg3: i32, arg4: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = ComponentIpSocketAddress::new(
                        T::new(
                            (arg0 as u8, arg1 as u8, arg2 as u8, arg3 as u8),
                            arg4 as u16,
                        ),
                    );
                    (result0).take_handle() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_component_pollable_block_cabi<
                    T: GuestComponentPollable,
                >(arg0: *mut u8) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::block(ComponentPollableBorrow::lift(arg0 as u32 as usize).get());
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_component_pollable_ready_cabi<
                    T: GuestComponentPollable,
                >(arg0: *mut u8) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::ready(
                        ComponentPollableBorrow::lift(arg0 as u32 as usize).get(),
                    );
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_constructor_component_network_cabi<
                    T: GuestComponentNetwork,
                >() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = ComponentNetwork::new(T::new());
                    (result0).take_handle() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_component_tcp_socket_bind_cabi<
                    T: GuestComponentTcpSocket,
                >(arg0: *mut u8, arg1: i32, arg2: i32) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::bind(
                        ComponentTcpSocketBorrow::lift(arg0 as u32 as usize).get(),
                        ComponentNetworkBorrow::lift(arg1 as u32 as usize),
                        ComponentIpSocketAddress::from_handle(arg2 as u32),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_component_tcp_socket_listen_cabi<
                    T: GuestComponentTcpSocket,
                >(arg0: *mut u8) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::listen(
                        ComponentTcpSocketBorrow::lift(arg0 as u32 as usize).get(),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_component_tcp_socket_local_address_cabi<
                    T: GuestComponentTcpSocket,
                >(arg0: *mut u8) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::local_address(
                        ComponentTcpSocketBorrow::lift(arg0 as u32 as usize).get(),
                    );
                    (result0).take_handle() as i32
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_component_tcp_socket_is_listening_cabi<
                    T: GuestComponentTcpSocket,
                >(arg0: *mut u8) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::is_listening(
                        ComponentTcpSocketBorrow::lift(arg0 as u32 as usize).get(),
                    );
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_component_tcp_socket_subscribe_cabi<
                    T: GuestComponentTcpSocket,
                >(arg0: *mut u8) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::subscribe(
                        ComponentTcpSocketBorrow::lift(arg0 as u32 as usize).get(),
                    );
                    (result0).take_handle() as i32
                }
                pub trait Guest {
                    type ComponentIpSocketAddress: GuestComponentIpSocketAddress;
                    type ComponentPollable: GuestComponentPollable;
                    type ComponentNetwork: GuestComponentNetwork;
                    type ComponentTcpSocket: GuestComponentTcpSocket;
                }
                pub trait GuestComponentIpSocketAddress: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> u32
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = val;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]pkg:component/component-tcp"
                            )]
                            extern "C" {
                                #[link_name = "[resource-new]component-ip-socket-address"]
                                fn new(_: *mut u8) -> u32;
                            }
                            new(val)
                        }
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: u32) -> *mut u8
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = handle;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]pkg:component/component-tcp"
                            )]
                            extern "C" {
                                #[link_name = "[resource-rep]component-ip-socket-address"]
                                fn rep(_: u32) -> *mut u8;
                            }
                            unsafe { rep(handle) }
                        }
                    }
                    fn new(address: (u8, u8, u8, u8), port: u16) -> Self;
                }
                pub trait GuestComponentPollable: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> u32
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = val;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]pkg:component/component-tcp"
                            )]
                            extern "C" {
                                #[link_name = "[resource-new]component-pollable"]
                                fn new(_: *mut u8) -> u32;
                            }
                            new(val)
                        }
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: u32) -> *mut u8
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = handle;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]pkg:component/component-tcp"
                            )]
                            extern "C" {
                                #[link_name = "[resource-rep]component-pollable"]
                                fn rep(_: u32) -> *mut u8;
                            }
                            unsafe { rep(handle) }
                        }
                    }
                    fn block(&self);
                    fn ready(&self) -> bool;
                }
                pub trait GuestComponentNetwork: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> u32
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = val;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]pkg:component/component-tcp"
                            )]
                            extern "C" {
                                #[link_name = "[resource-new]component-network"]
                                fn new(_: *mut u8) -> u32;
                            }
                            new(val)
                        }
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: u32) -> *mut u8
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = handle;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]pkg:component/component-tcp"
                            )]
                            extern "C" {
                                #[link_name = "[resource-rep]component-network"]
                                fn rep(_: u32) -> *mut u8;
                            }
                            unsafe { rep(handle) }
                        }
                    }
                    fn new() -> Self;
                }
                pub trait GuestComponentTcpSocket: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> u32
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = val;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]pkg:component/component-tcp"
                            )]
                            extern "C" {
                                #[link_name = "[resource-new]component-tcp-socket"]
                                fn new(_: *mut u8) -> u32;
                            }
                            new(val)
                        }
                    }
                    #[doc(hidden)]
                    fn _resource_rep(handle: u32) -> *mut u8
                    where
                        Self: Sized,
                    {
                        #[cfg(not(target_arch = "wasm32"))]
                        {
                            let _ = handle;
                            unreachable!();
                        }
                        #[cfg(target_arch = "wasm32")]
                        {
                            #[link(
                                wasm_import_module = "[export]pkg:component/component-tcp"
                            )]
                            extern "C" {
                                #[link_name = "[resource-rep]component-tcp-socket"]
                                fn rep(_: u32) -> *mut u8;
                            }
                            unsafe { rep(handle) }
                        }
                    }
                    fn bind(
                        &self,
                        network: ComponentNetworkBorrow<'_>,
                        socket: ComponentIpSocketAddress,
                    );
                    fn listen(&self);
                    fn local_address(&self) -> ComponentIpSocketAddress;
                    fn is_listening(&self) -> bool;
                    fn subscribe(&self) -> ComponentPollable;
                }
                #[doc(hidden)]
                macro_rules! __export_pkg_component_component_tcp_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[export_name =
                        "pkg:component/component-tcp#[constructor]component-ip-socket-address"]
                        unsafe extern "C" fn
                        export_constructor_component_ip_socket_address(arg0 : i32, arg1 :
                        i32, arg2 : i32, arg3 : i32, arg4 : i32,) -> i32 {
                        $($path_to_types)*::
                        _export_constructor_component_ip_socket_address_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::ComponentIpSocketAddress > (arg0,
                        arg1, arg2, arg3, arg4) } #[export_name =
                        "pkg:component/component-tcp#[method]component-pollable.block"]
                        unsafe extern "C" fn export_method_component_pollable_block(arg0
                        : * mut u8,) { $($path_to_types)*::
                        _export_method_component_pollable_block_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::ComponentPollable > (arg0) }
                        #[export_name =
                        "pkg:component/component-tcp#[method]component-pollable.ready"]
                        unsafe extern "C" fn export_method_component_pollable_ready(arg0
                        : * mut u8,) -> i32 { $($path_to_types)*::
                        _export_method_component_pollable_ready_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::ComponentPollable > (arg0) }
                        #[export_name =
                        "pkg:component/component-tcp#[constructor]component-network"]
                        unsafe extern "C" fn export_constructor_component_network() ->
                        i32 { $($path_to_types)*::
                        _export_constructor_component_network_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::ComponentNetwork > () }
                        #[export_name =
                        "pkg:component/component-tcp#[method]component-tcp-socket.bind"]
                        unsafe extern "C" fn export_method_component_tcp_socket_bind(arg0
                        : * mut u8, arg1 : i32, arg2 : i32,) { $($path_to_types)*::
                        _export_method_component_tcp_socket_bind_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::ComponentTcpSocket > (arg0, arg1,
                        arg2) } #[export_name =
                        "pkg:component/component-tcp#[method]component-tcp-socket.listen"]
                        unsafe extern "C" fn
                        export_method_component_tcp_socket_listen(arg0 : * mut u8,) {
                        $($path_to_types)*::
                        _export_method_component_tcp_socket_listen_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::ComponentTcpSocket > (arg0) }
                        #[export_name =
                        "pkg:component/component-tcp#[method]component-tcp-socket.local-address"]
                        unsafe extern "C" fn
                        export_method_component_tcp_socket_local_address(arg0 : * mut
                        u8,) -> i32 { $($path_to_types)*::
                        _export_method_component_tcp_socket_local_address_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::ComponentTcpSocket > (arg0) }
                        #[export_name =
                        "pkg:component/component-tcp#[method]component-tcp-socket.is-listening"]
                        unsafe extern "C" fn
                        export_method_component_tcp_socket_is_listening(arg0 : * mut u8,)
                        -> i32 { $($path_to_types)*::
                        _export_method_component_tcp_socket_is_listening_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::ComponentTcpSocket > (arg0) }
                        #[export_name =
                        "pkg:component/component-tcp#[method]component-tcp-socket.subscribe"]
                        unsafe extern "C" fn
                        export_method_component_tcp_socket_subscribe(arg0 : * mut u8,) ->
                        i32 { $($path_to_types)*::
                        _export_method_component_tcp_socket_subscribe_cabi::<<$ty as
                        $($path_to_types)*:: Guest >::ComponentTcpSocket > (arg0) } const
                        _ : () = { #[doc(hidden)] #[export_name =
                        "pkg:component/component-tcp#[dtor]component-ip-socket-address"]
                        #[allow(non_snake_case)] unsafe extern "C" fn dtor(rep : * mut
                        u8) { $($path_to_types)*:: ComponentIpSocketAddress::dtor::< <$ty
                        as $($path_to_types)*:: Guest >::ComponentIpSocketAddress > (rep)
                        } }; const _ : () = { #[doc(hidden)] #[export_name =
                        "pkg:component/component-tcp#[dtor]component-pollable"]
                        #[allow(non_snake_case)] unsafe extern "C" fn dtor(rep : * mut
                        u8) { $($path_to_types)*:: ComponentPollable::dtor::< <$ty as
                        $($path_to_types)*:: Guest >::ComponentPollable > (rep) } };
                        const _ : () = { #[doc(hidden)] #[export_name =
                        "pkg:component/component-tcp#[dtor]component-network"]
                        #[allow(non_snake_case)] unsafe extern "C" fn dtor(rep : * mut
                        u8) { $($path_to_types)*:: ComponentNetwork::dtor::< <$ty as
                        $($path_to_types)*:: Guest >::ComponentNetwork > (rep) } }; const
                        _ : () = { #[doc(hidden)] #[export_name =
                        "pkg:component/component-tcp#[dtor]component-tcp-socket"]
                        #[allow(non_snake_case)] unsafe extern "C" fn dtor(rep : * mut
                        u8) { $($path_to_types)*:: ComponentTcpSocket::dtor::< <$ty as
                        $($path_to_types)*:: Guest >::ComponentTcpSocket > (rep) } }; };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_pkg_component_component_tcp_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicU32, Ordering::Relaxed};
    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        handle: AtomicU32,
        _marker: marker::PhantomData<T>,
    }
    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: u32);
    }
    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
            debug_assert!(handle != u32::MAX);
            Self {
                handle: AtomicU32::new(handle),
                _marker: marker::PhantomData,
            }
        }
        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> u32 {
            resource.handle.swap(u32::MAX, Relaxed)
        }
        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> u32 {
            resource.handle.load(Relaxed)
        }
    }
    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource").field("handle", &self.handle).finish()
        }
    }
    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    u32::MAX => {}
                    other => T::drop(other),
                }
            }
        }
    }
    pub use alloc_crate::boxed::Box;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_component_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::pkg::component::component_tcp::__export_pkg_component_component_tcp_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::pkg::component::component_tcp);
    };
}
#[doc(inline)]
pub(crate) use __export_component_impl as export;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:pkg:component:component:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 811] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xab\x05\x01A\x02\x01\
A\x02\x01B\x1d\x04\0\x1bcomponent-ip-socket-address\x03\x01\x04\0\x12component-p\
ollable\x03\x01\x04\0\x11component-network\x03\x01\x04\0\x14component-tcp-socket\
\x03\x01\x01o\x04}}}}\x01i\0\x01@\x02\x07address\x04\x04port{\0\x05\x04\0([const\
ructor]component-ip-socket-address\x01\x06\x01h\x01\x01@\x01\x04self\x07\x01\0\x04\
\0\x20[method]component-pollable.block\x01\x08\x01@\x01\x04self\x07\0\x7f\x04\0\x20\
[method]component-pollable.ready\x01\x09\x01i\x02\x01@\0\0\x0a\x04\0\x1e[constru\
ctor]component-network\x01\x0b\x01h\x03\x01h\x02\x01@\x03\x04self\x0c\x07network\
\x0d\x06socket\x05\x01\0\x04\0![method]component-tcp-socket.bind\x01\x0e\x01@\x01\
\x04self\x0c\x01\0\x04\0#[method]component-tcp-socket.listen\x01\x0f\x01@\x01\x04\
self\x0c\0\x05\x04\0*[method]component-tcp-socket.local-address\x01\x10\x01@\x01\
\x04self\x0c\0\x7f\x04\0)[method]component-tcp-socket.is-listening\x01\x11\x01i\x01\
\x01@\x01\x04self\x0c\0\x12\x04\0&[method]component-tcp-socket.subscribe\x01\x13\
\x04\0\x1bpkg:component/component-tcp\x05\0\x04\0\x17pkg:component/component\x04\
\0\x0b\x0f\x01\0\x09component\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0d\
wit-component\x070.220.1\x10wit-bindgen-rust\x060.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
